@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: !TEST_FUNC!: ERROR=`!TEST_IMPL_ERROR!` RESULT=`!STRING_OUTPUT!` INPUT=`!STRING_INPUT!`
  echo;
  exit /b 0
)

echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: !TEST_FUNC!: INPUT=`!STRING_INPUT!`

exit /b 0
