@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;FAILED: !TESTLIB__TEST_ORDER_NUMBER!: RESULT=`!STRING_TRIMMED!` REFERENCE=`!STRING_REFERENCE!`
  echo;
  exit /b 0
)

echo;PASSED: !TESTLIB__TEST_ORDER_NUMBER!: RESULT=`!STRING_TRIMMED!`

exit /b 0
