@echo off

:TRIM_RIGHT_LOOP
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
( if not defined RETURN_VALUE exit /b 0 ) & ( if not ^%RETURN_VALUE:~-1%/ == ^ / if not ^%RETURN_VALUE:~-1%/ == ^	/ exit /b 0 ) & setlocal ENABLEDELAYEDEXPANSION & if not "!RETURN_VALUE:~0,-1!" == "" ( for /F "eol= tokens=* delims=" %%i in ("!RETURN_VALUE:~0,-1!") do endlocal & set "RETURN_VALUE=%%i" ) else ( endlocal & set "RETURN_VALUE=" & exit /b 0 )
goto TRIM_RIGHT_LOOP
