@echo off

set "TEST_DATA_REF_DIR=%~1"
set "TEST_DATA_REF_DIR=%TEST_DATA_REF_DIR:\=/%"

set "TEST_TEMP_DIR_NAME=%TEST_SCRIPT_FILE_NAME%.%TESTLIB__CURRENT_TESTS%.%RANDOM%_%RANDOM%"

call :CANONICAL_PATH TEST_TEMP_DIR "%%TEST_TEMP_BASE_DIR%%\%%TEST_TEMP_DIR_NAME%%"

if not defined TEST_TEMP_DIR exit /b 127

mkdir "%TEST_TEMP_DIR%"

exit /b 0

:CANONICAL_PATH
setlocal DISABLEDELAYEDEXPANSION
set "RETURN_VALUE=%~dpf2"
set "RETURN_VALUE=%RETURN_VALUE:\=/%"
if "%RETURN_VALUE:~-1%" == "/" set "RETURN_VALUE=%RETURN_VALUE:~0,-1%"
(
  endlocal
  set "%~1=%RETURN_VALUE%"
)
exit /b 0
