@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;FAILED: !TESTLIB__TEST_ORDER_NUMBER!: ERROR=`!TEST_IMPL_ERROR!` CURRENT_CP=`!CURRENT_CP!==!CURRENT_CP_REF!` LAST_CP=`!LAST_CP!==!LAST_CP_REF!` CP_HISTORY_LIST=`!CP_HISTORY_LIST!==!CP_HISTORY_LIST_REF!`"
  echo;
  exit /b 0
)

echo;PASSED: !TESTLIB__TEST_ORDER_NUMBER!: ERROR=`!TEST_IMPL_ERROR!` CURRENT_CP=`!CURRENT_CP!` LAST_CP=`!LAST_CP!` CP_HISTORY_LIST=`!CP_HISTORY_LIST!`

exit /b 0
