@echo off

setlocal DISABLEDELAYEDEXPANSION

call "%%CONTOOLS_BUILD_TOOLS_ROOT%%/load_config.bat" -- . . "%%CONFIG_FILE%%" "%%PARAM0%%" "%%PARAM1%%"

echo;PARAM0=%PARAM0%
echo;PARAM1=%PARAM1%

set TEST_IMPL_ERROR=0
set TEST_VAR_CASE_INDEX=1

for %%i in (%TEST_VAR_NAME_SUFFIX_LIST%) do (
  set "TEST_VAR_NAME=%TEST_VAR_NAME_PREFIX%%%i"
  set "REFERENCE_VAR_NAME=%REFERENCE_VAR_NAME_PREFIX%%%i"
  call :TEST
)

echo;

endlocal & set "TEST_IMPL_ERROR=%TEST_IMPL_ERROR%"

exit /b 0

:TEST
setlocal ENABLEDELAYEDEXPANSION

call "%%CONTOOLS_ROOT%%/std/cmp_var.bat" "%%TEST_VAR_NAME%%" EQU "%%REFERENCE_VAR_NAME%%" && (
  echo;PASSED: !TESTLIB__TEST_ORDER_NUMBER!''!TEST_VAR_CASE_INDEX!: VAR=`!TEST_VAR_NAME!` RESULT=`!%TEST_VAR_NAME%!`
  call;
) || (
  set /A "TEST_IMPL_ERROR|=0x80000000"
  echo;FAILED: !TESTLIB__TEST_ORDER_NUMBER!''!TEST_VAR_CASE_INDEX!: VAR=`!TEST_VAR_NAME!` RESULT=`!%TEST_VAR_NAME%!` REFERENCE=`!%REFERENCE_VAR_NAME%!`
  echo;
)

(
  endlocal
  set "TEST_IMPL_ERROR=%TEST_IMPL_ERROR%"
  set /A TEST_VAR_CASE_INDEX+=1
)
