@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: (!TEST_IMPL_ERROR! == !TEST_PREV_ERROR!^) REF=`!VARREF!` LVALUE=`!%LVAR%!` RVAR=`!RVAR!`
  echo;
  exit /b 0
)

echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: ERR=`!TEST_IMPL_ERROR!` LVALUE=`!%LVAR%!` RVAR=`!RVAR!`

exit /b 0
