#pragma once

#ifndef _NTSEAPI_H
#define _NTSEAPI_H

#define SE_ASSIGNPRIMARYTOKEN_PRIVILEGE (3L)

#define SE_INCREASE_QUOTA_PRIVILEGE (5L)

#define SE_TCB_PRIVILEGE (7L)

#define SE_DEBUG_PRIVILEGE (20L)

#define SE_DELEGATE_SESSION_USER_IMPERSONATE_PRIVILEGE (36L)

#define SE_MAX_WELL_KNOWN_PRIVILEGE SE_DELEGATE_SESSION_USER_IMPERSONATE_PRIVILEGE

#endif
