@echo off

set "TEST_DATA_DIR=%TEST_SCRIPT_FILE_NAME%/%~1"
shift

set "TEST_DATA_SED_CMD_LINE="
:TEST_DATA_SED_CMD_LINE_LOOP
if "%~1" == "" goto TEST_DATA_SED_CMD_LINE_LOOP_END

set TEST_DATA_SED_CMD_LINE=%TEST_DATA_SED_CMD_LINE%%1 
shift

goto TEST_DATA_SED_CMD_LINE_LOOP

:TEST_DATA_SED_CMD_LINE_LOOP_END

exit /b 0
