@echo off

if %LASTERROR% NEQ 0 (
  echo.FAILED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__TEST_COUNT%: ERROR=%LASTERROR%.%INTERRORLEVEL% REFERENCE=`%TEST_DATA_REF_FILE%` OUTPUT=`%TEST_SRC_BASE_DIR%\_output\%TEST_TEMP_DIR_NAME%`
  echo.
  exit /b 0
)

echo.PASSED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__TEST_COUNT%: REFERENCE=`%TEST_DATA_REF_FILE%`

exit /b 0
