@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: RET=`!TEST_IMPL_ERROR!` RETREF=`!RETREF!` OUTREF=`!OUTREF!` OUT=`!OUT!` IN=`!IN!`
  echo;
  exit /b 0
)

echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: RET=`!TEST_IMPL_ERROR!` OUT=`!OUT!` IN=`!IN!`

exit /b 0
