@echo off

setlocal

call "%%CONTOOLS_ROOT%%/std/trim_var.bat" STRING_TO_TRIM STRING_TRIMMED

if %TESTLIB__OVERALL_TESTS% GTR %TESTLIB__CURRENT_TESTS% (
  set "TEST_REPORT_PREFIX_STR=%TESTLIB__OVERALL_TESTS%`%TESTLIB__CURRENT_TESTS%"
) else set "TEST_REPORT_PREFIX_STR=%TESTLIB__CURRENT_TESTS%"

"%CONTOOLS_UTILS_BIN_ROOT%/contools/envvarcmp.exe" STRING_TRIMMED STRING_REFERENCE "" ^
  "PASSED: %TEST_REPORT_PREFIX_STR%: RESULT=`{0}`" ^
  "FAILED: %TEST_REPORT_PREFIX_STR%: RESULT=`{0}` REFERENCE=`{1}`"
if %ERRORLEVEL% NEQ 0 (
  exit /b 1
)

exit /b 0
