@echo off

if %LAST_ERROR% NEQ 0 (
  echo;FAILED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__CURRENT_TESTS%: ERROR=%LAST_ERROR%.%INTERRORLEVEL% REFERENCE=`%TEST_DATA_REF_FILE%` OUTPUT=`%TEST_DATA_OUT_DIR%\%TEST_TEMP_DIR_NAME%`
  echo;
  exit /b 0
)

echo;PASSED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__CURRENT_TESTS%: REFERENCE=`%TEST_DATA_REF_FILE%`

exit /b 0
