if(NOT ENV_FILENAME)
    set(ENV_FILENAME "environment.cmake")
endif()
if("${ENV_ROOT}" STREQUAL "")
    if(EXISTS "${PROJECT_SOURCE_DIR}/${ENV_FILENAME}")
        # use environment file root as project source directory
        set(ENV_ROOT "${PROJECT_SOURCE_DIR}")
    elseif(DEFINED ENV{ENV_ROOT})
        # use environment file root as environment variable value
        set(ENV_ROOT "$ENV{ENV_ROOT}")
    endif()
endif()
if(NOT "${ENV_ROOT}" STREQUAL "")
    # extract environment file root components
    set(ENV_FILE "${ENV_ROOT}/${ENV_FILENAME}")
    get_filename_component(ENV_FILE "${ENV_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()
if(EXISTS "${ENV_FILE}")
    # includes environment file from path found before or from current directory
    message(STATUS "(*) Environment found: ENV_ROOT=\"${ENV_ROOT}\" ENV_FILENAME=\"${ENV_FILENAME}\"")
    get_filename_component(ENV_ROOT "${ENV_FILE}" DIRECTORY)
    set(ENV_ROOT "${ENV_ROOT}" CACHE PATH "${ENV_FILENAME} directory")
    include("${ENV_FILE}")
else()
    if(NOT "${ENV_ROOT}" STREQUAL "") # some malformed user defined path
        message(FATAL_ERROR "Invalid environment root: ENV_ROOT=\"${ENV_ROOT}\" ENV_FILENAME=\"${ENV_FILENAME}\"")
    else()
        unset(ENV_ROOT CACHE)
        message(STATUS "(*) Environment root directory is empty: ENV_ROOT=\"${ENV_ROOT}\" ENV_FILENAME=\"${ENV_FILENAME}\".")
    endif()
endif()
