@echo off

if /i "%CONTOOLS_ROOT_INIT0_DIR%" == "%~dp0" exit /b

set "CONTOOLS_ROOT_INIT0_DIR=%~dp0"

if not defined NEST_LVL set NEST_LVL=0

set "CONFIGURE_ROOT=%~dp0.."
set "CONFIGURE_ROOT=%CONFIGURE_ROOT:\=/%"
if "%CONFIGURE_ROOT:~-1%" == "/" set "CONFIGURE_ROOT=%CONFIGURE_ROOT:~0,-1%"

if not defined LOCAL_CONFIG_DIR_NAME set "LOCAL_CONFIG_DIR_NAME=config"

if not defined CONTOOLS_ROOT set "CONTOOLS_ROOT=%CONFIGURE_ROOT%/Scripts/Tools"
set "CONTOOLS_ROOT=%CONTOOLS_ROOT:\=/%"
if "%CONTOOLS_ROOT:~-1%" == "/" set "CONTOOLS_ROOT=%CONTOOLS_ROOT:~0,-1%"

if not defined UTILITIES_ROOT set "UTILITIES_ROOT=%CONFIGURE_ROOT%/Utilities"
set "UTILITIES_ROOT=%UTILITIES_ROOT:\=/%"
if "%UTILITIES_ROOT:~-1%" == "/" set "UTILITIES_ROOT=%UTILITIES_ROOT:~0,-1%"

if not defined UTILITY_ROOT set "UTILITY_ROOT=%UTILITIES_ROOT%/bin"
set "UTILITY_ROOT=%UTILITY_ROOT:\=/%"
if "%UTILITY_ROOT:~-1%" == "/" set "UTILITY_ROOT=%UTILITY_ROOT:~0,-1%"

if not defined BUILD_TOOLS_ROOT set "BUILD_TOOLS_ROOT=%CONTOOLS_ROOT%/build"
set "BUILD_TOOLS_ROOT=%BUILD_TOOLS_ROOT:\=/%"
if "%BUILD_TOOLS_ROOT:~-1%" == "/" set "BUILD_TOOLS_ROOT=%BUILD_TOOLS_ROOT:~0,-1%"

if not defined GNUWIN32_ROOT set "GNUWIN32_ROOT=%CONTOOLS_ROOT%/gnuwin32"
set "GNUWIN32_ROOT=%GNUWIN32_ROOT:\=/%"
if "%GNUWIN32_ROOT:~-1%" == "/" set "GNUWIN32_ROOT=%GNUWIN32_ROOT:~0,-1%"

if not defined SVNCMD_TOOLS_ROOT set "SVNCMD_TOOLS_ROOT=%CONTOOLS_ROOT%/scm/svn"
set "SVNCMD_TOOLS_ROOT=%SVNCMD_TOOLS_ROOT:\=/%"
if "%SVNCMD_TOOLS_ROOT:~-1%" == "/" set "SVNCMD_TOOLS_ROOT=%SVNCMD_TOOLS_ROOT:~0,-1%"

if not defined SQLITE_TOOLS_ROOT set "SQLITE_TOOLS_ROOT=%CONTOOLS_ROOT%/sqlite"
set "SQLITE_TOOLS_ROOT=%SQLITE_TOOLS_ROOT:\=/%"
if "%SQLITE_TOOLS_ROOT:~-1%" == "/" set "SQLITE_TOOLS_ROOT=%SQLITE_TOOLS_ROOT:~0,-1%"

if not defined TESTLIB_ROOT set "TESTLIB_ROOT=%CONTOOLS_ROOT%/testlib"
set "TESTLIB_ROOT=%TESTLIB_ROOT:\=/%"
if "%TESTLIB_ROOT:~-1%" == "/" set "TESTLIB_ROOT=%TESTLIB_ROOT:~0,-1%"

if not defined XML_TOOLS_ROOT set "XML_TOOLS_ROOT=%CONTOOLS_ROOT%/xml"
set "XML_TOOLS_ROOT=%XML_TOOLS_ROOT:\=/%"
if "%XML_TOOLS_ROOT:~-1%" == "/" set "XML_TOOLS_ROOT=%XML_TOOLS_ROOT:~0,-1%"

if not defined HASHDEEP_ROOT set "HASHDEEP_ROOT=%CONTOOLS_ROOT%/hash/hashdeep"
set "HASHDEEP_ROOT=%HASHDEEP_ROOT:\=/%"
if "%HASHDEEP_ROOT:~-1%" == "/" set "HASHDEEP_ROOT=%HASHDEEP_ROOT:~0,-1%"

if not defined VARS_ROOT set "VARS_ROOT=%CONTOOLS_ROOT%/vars"
set "VARS_ROOT=%VARS_ROOT:\=/%"
if "%VARS_ROOT:~-1%" == "/" set "VARS_ROOT=%VARS_ROOT:~0,-1%"

exit /b 0
