@echo off

setlocal

call "%%CONTOOLS_ROOT%%/extract_version.bat" "%%VERSION_IN%%" %%TEST_DATA_CMD_LINE%%
set "ERRORLEVEL_RETURNED=%ERRORLEVEL%"
set "VERSION_RETURNED=%RETURN_VALUE%"

if %ERRORLEVEL_RETURNED% NEQ 0 (
  call "%CONTOOLS_UTILS_BIN_ROOT%/contools/envvarcmp.exe" VERSION_RETURNED VERSION_REF "" ^
    "FAILED: %TESTLIB__TEST_ORDER_NUMBER%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}` REFERENCE=`{1}`" ^
    "FAILED: %TESTLIB__TEST_ORDER_NUMBER%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}` REFERENCE=`{1}` (`{0hs}` != `{1hs}`)"
  exit /b 1
)

"%CONTOOLS_UTILS_BIN_ROOT%/contools/envvarcmp.exe" VERSION_RETURNED VERSION_REF "" ^
  "PASSED: %TESTLIB__TEST_ORDER_NUMBER%: RESULT=`{0}`" ^
  "FAILED: %TESTLIB__TEST_ORDER_NUMBER%: RESULT=`{0}` REFERENCE=`{1}` (`{0hs}` != `{1hs}`)" || exit /b 2

exit /b 0
