@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;FAILED: !TESTLIB__TEST_ORDER_NUMBER!: ERROR=`!TEST_IMPL_ERROR!` RESULT=`!VERSION_RETURNED!` REFERENCE=`!VERSION_REF!`
  echo;
  exit /b 0
)

echo;PASSED: !TESTLIB__TEST_ORDER_NUMBER!: RESULT=`!VERSION_RETURNED!`

exit /b 0
