@echo off

setlocal ENABLEDELAYEDEXPANSION

if !TEST_LAST_ERROR! NEQ 0 (
  echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: RESULT=`!TEST_IMPL_ERROR!` REFERENCE=`!RETURN_REFERENCE!` CMDLINE=`!PREFIXED_CMDLINE!`
  echo;
  exit /b 0
)

echo;!TESTLIB__TEST_STATUS_MSG!: !TESTLIB__TEST_ORDER_NUMBER!: RESULT=`!TEST_IMPL_ERROR!` CMDLINE=`!PREFIXED_CMDLINE!`

exit /b 0
