@echo off

if %TEST_LAST_ERROR% NEQ 0 (
  echo;FAILED: %TESTLIB__TEST_ORDER_NUMBER%: ERROR=%TEST_LAST_ERROR%.%TEST_IMPL_ERROR% REFERENCE=`%TEST_DATA_FILE_IN_OUT_DIR%` OUTPUT=`%TEST_DATA_OUT_ROOT%\%TEST_TEMP_DIR_NAME%`
  echo;
  exit /b 0
)

echo;PASSED: %TESTLIB__TEST_ORDER_NUMBER%: REFERENCE=`%TEST_DATA_FILE_IN_OUT_DIR%`

exit /b 0
