@echo off

setlocal

if %TESTLIB__OVERALL_TESTS% GTR %TESTLIB__TEST_COUNT% (
  set "TEST_REPORT_PREFIX_STR=%TESTLIB__OVERALL_TESTS%`%TESTLIB__TEST_COUNT%"
) else set "TEST_REPORT_PREFIX_STR=%TESTLIB__TEST_COUNT%"

if %ERRORLEVEL_RETURNED% NEQ 0 (
  call "%CONTOOLS_ROOT%/envvarcmp.exe" VERSION_RETURNED VERSION_REF "" ^
    "FAILED: %TEST_REPORT_PREFIX_STR%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}` REFERENCE=`{1}`" ^
    "FAILED: %TEST_REPORT_PREFIX_STR%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}` REFERENCE=`{1}` (`{0hs}` != `{1hs}`)"
  echo.
  exit /b 1
)

"%CONTOOLS_ROOT%/envvarcmp.exe" VERSION_RETURNED VERSION_REF "" ^
  "PASSED: %TEST_REPORT_PREFIX_STR%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}`" ^
  "FAILED: %TEST_REPORT_PREFIX_STR%: ERRORLEVEL=%ERRORLEVEL_RETURNED% RESULT=`{0}` REFERENCE=`{1}` (`{0hs}` != `{1hs}`)"
if %ERRORLEVEL% NEQ 0 (
  echo.
  exit /b 2
)

exit /b 0
