@echo off

if %TEST_LAST_ERROR% NEQ 0 (
  echo;FAILED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__CURRENT_TESTS%: ERROR=%TEST_LAST_ERROR%.%TEST_IMPL_ERROR% REFERENCE=`%TEST_DATA_FILE_REF_DIR%` OUTPUT=`%TEST_DATA_OUT_ROOT%\%TEST_TEMP_DIR_NAME%`
  echo;
  exit /b 0
)

echo;PASSED: %TESTLIB__OVERALL_TESTS%.%TESTLIB__CURRENT_TESTS%: REFERENCE=`%TEST_DATA_FILE_REF_DIR%`

exit /b 0
