@echo off

setlocal

call "%%CONTOOLS_BUILD_TOOLS_ROOT%%/load_config.bat" . . "%%CONFIG_FILE%%" "%%PARAM0%%" "%%PARAM1%%"

echo;PARAM0=%PARAM0%
echo;PARAM1=%PARAM1%

set TEST_LAST_ERROR=0
set TEST_VAR_CASE_INDEX=1
for %%i in (%TEST_VAR_NAME_SUFFIX_LIST%) do (
  "%CONTOOLS_UTILS_BIN_ROOT%/contools/envvarcmp.exe" %TEST_VAR_NAME_PREFIX%%%i %REFERENCE_VAR_NAME_PREFIX%%%i "" ^
    "PASSED: %TESTLIB__TEST_ORDER_NUMBER%`${TEST_VAR_CASE_INDEX}: VAR=`${TEST_VAR_NAME_PREFIX}%%i` RESULT=`{0}`" ^
    "FAILED: %TESTLIB__TEST_ORDER_NUMBER%`${TEST_VAR_CASE_INDEX}: VAR=`${TEST_VAR_NAME_PREFIX}%%i` RESULT=`{0}` REFERENCE=`{1}`" || set /A "TEST_LAST_ERROR|=0x80000000"
  set /A TEST_VAR_CASE_INDEX+=1
)

echo;

exit /b %TEST_LAST_ERROR%
